### ISSUE TITLE
CrisisCenter bug: CanDeactivate not used as the generic interface it is

### ISSUE THREAD

**Issue by wardbell** [brandonroberts/vladivostok-sample#10]
One of the problems of this implementation is we (maybe just "I") not getting intellisense. 

Therefore can't see (and in-browser transpiler not telling us) that this is an error

```
export class CanDeactivateCrisisDetail implements CanDeactivate {
```

and should be

```
export class CanDeactivateCrisisDetail implements CanDeactivate<CrisisDetailComponent> {
```

**Comment by brandonroberts** [comment]
Closed via 00a10648a55d93fce5b6597d84f0f66dd4a87b4e
