### ISSUE TITLE
Feature: option to load ROUTER_DIRECTIVES into PLATFORM_DIRECTIVES.

### ISSUE THREAD

**Issue by wardbell** [brandonroberts/vladivostok-sample#18]
So that we don't keep writing `directives: [ROUTER_DIRECTIVES],` everywhere

**Comment by brandonroberts** [comment]
After discussing this one, we decided to allow the router to be placed in the main app component `providers` and give direction on how to make the ROUTER_DIRECTIVES global using the bootstrap array.
